---
title: "Registro de pacientes que sufrieron insuficiencia cardiaca"
author: "Jenny y Corina"
format: html
toc: true
lang: es
theme: yeti
---

# Introduccion

[fuente de datos](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-020-1023-5)
La finalidad de este trabajo es mostrar el resultado de cada consulta, tanto en hombres y mujeres utilizando [fuente de datos](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-020-1023-5)

# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(dplyr)
```

# Carga de datos

```{r}
#| label: carga-datos
#| message: false
#| warning: false

pacientes <- 
  read_csv("heart_failure_clinical_records_dataset.csv")
```

## Consulta 1

```{r}
 #| label: Consulta-01

# Hombres mayores de 70 años, diabeticos y no anemicos mostrados en orden descendente

pacientes |>
  filter(sex == "1" & diabetes == "1" & anaemia == "0" & high_blood_pressure == "1" & age >= 70) |>
  select(age, sex, diabetes, anaemia, high_blood_pressure)|>
  arrange(desc(age))|>
kable()
```

## Consulta 2

```{r}
 #| label: Consulta-02

# Mujeres con fracción de eyección entre 20 y 25, en orden descendente de fracción de eyección

pacientes |>
  filter(sex == "0") |>
  select(sex, ejection_fraction, anaemia, diabetes)|>
  arrange(desc(ejection_fraction))|>
kable()
```

## Consulta-03

 
```{r}
#| label: Consulta-03

# Tabla que muestre el promedio de creatinina sérica de pacientes sobrevivientes y de pacientes fallecidos

pacientes |>
select(serum_creatinine, DEATH_EVENT)|>
   
  kable()
```

## Consulta-04


```{r}
#| label: Consulta-04

pacientes |>
 filter(sex == "0" & diabetes == "1" & anaemia == "1") |>
select(sex, serum_creatinine, anaemia, diabetes)


 
```














